name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
  
    # - name: Cache SonarCloud packages
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.sonar/cache
    #     key: ${{ runner.os }}-sonar
      
    # - name: Run SonarCloud Scan
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKER }}
    #   run: |
    #     npx sonar-scanner \
    #       -Dsonar.projectKey=svaklinov_monitoring \
    #       -Dsonar.organization=svaklinov \
    #       -Dsonar.sources=. \
    #       -Dsonar.host.url=https://sonarcloud.io \
    #       -Dsonar.login=${{ secrets.SONAR_CLOUD_TOKER }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest

    - name: Run container for test
      run: |
        docker run -d --name monitoring -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest
        sleep 3        
        curl -f http://localhost        
        # docker exec monitoring curl -f http://localhost:8000 -f argument give option curl to fail if is not sussesful        

    - name: Cleanup
      run: |        
        docker rm -f monitoring    

    - name: Install Snyk
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Test Docker image with Snyk
      run: snyk container test ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest

    - name: Monitor Docker image with Snyk
      run: snyk container monitor ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest
    
    - name: Connect to EC2 and Deploy image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |          
          docker stop $(docker ps -q) 
          docker rm $(docker ps -a -q)
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest
          docker run -d --name monitoring -p 80:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest